--- #YAML:1.0
name:               Mail-Postfix-Postdrop
version:            0.3
abstract:           Inject mails to a Postfix maildrop directory
author:
    - Peter Makholm <makholm@one.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Email::Abstract:  0
    Email::Address:   0
    Exporter:         5.57
    File::Temp:       0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
